### ISSUE TITLE
[FEAT] EMAIL TEMPLATES -> Subscription Renewal Failed Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#105]
## Description

_Create a Subscription Renewal Failed email template according to the design using React Email_

## Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Renewal Period
5. Update Payment Details Link
6. Any other required props

### Tests

- [x] Ensure template is responsive
- [x] Ensure template can receive dynamic data according to what will be displayed
- [x] Ensure template is displayed properly according to design and requirements

###  Tasks

- [x] Create one dynamic email template using React Email
- [x] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [x] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [x] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2266-9416&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Subscription Renewal Failed (3)](https://github.com/user-attachments/assets/528b49c3-62a1-4d6e-a749-3a882782db28)
![Subscription Renewal Failed (2)](https://github.com/user-attachments/assets/26215238-0ad9-4324-8e0b-e21625196f37)
![Subscription Renewal Failed (1)](https://github.com/user-attachments/assets/5f3cea2b-dcef-4b45-9951-e4f7a7c921ad)
![Subscription Renewal Failed](https://github.com/user-attachments/assets/eeb22c7e-ee1f-4224-902b-50a9519b6d51)
