### ISSUE TITLE
[FEATURE]  Create and implement the API integration of the comment section of the dynamic blog pages

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#106]
# **Description**
Implement both the web and mobile view of the blog details page comment section excluding and integrate the api to map out all comments on the blog also api to make new comments.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Show all current comments on the blog
- Text area to input comment with required validation
- Able to make new blog using the required api endpoint
- Realtime update of the rendered comment

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Friday 11:59 pm WAT

# **Tasks**
- [x] Implement all the sections in the design
- [x] Responsiveness across all screens
- [x] Make use of reusable components where needed
- [x] Write test for the implementations
- [x] Proper commit message

# **Images**
![Frame 53129](https://github.com/user-attachments/assets/b0548e35-ae17-4e45-b587-e1320260ef1a)
![Frame 53129](https://github.com/user-attachments/assets/a73470d7-e71d-4082-9468-982624cb83fe)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1632-11418&m=dev)

**Comment by CodeDeveloper19** [comment]
I am confused. The Figma design does not match the example image attached to this. For example, the Figma design I am looking at has a reply button, but it isn't included here. Or am I looking at the wrong design?

**Comment by chumex412** [comment]
Whoever is working on this task should also work on issues #72 and #73

**Comment by CodeDeveloper19** [comment]
Please, I still need help understanding which designs I am implementing. Am I to implement the design that I attached below? Because the Figma link design attached to the issue doesn't include any section that resembles the images attached to the issue. I would like my doubts cleared asap please so that I can begin work.
![Screenshot 2024-07-18 181906](https://github.com/user-attachments/assets/de96260c-d489-495a-aef4-45c5768da7fd)
