### ISSUE TITLE
[Enhancement]: No error message appears when an incorrect/empty input is entered in the "Create Role" form.

### ISSUE THREAD

**Issue by delight-xxx** [hngprojects/hng_boilerplate_nextjs#1084]
### Description

As an admin, I want to see a clear and immediate error message if any input field on the Create Role form is empty or incorrect, so I can correct it before submitting.

### Purpose
Admins should be alerted when the create role form is empty or a wrong input is given.

### Tasks

- [ ] Display an error message if the Role Description/Role Name field is left empty (e.g., "Role Description is required").
- [ ] Display an error message if the Role Description does not meet the length requirements (e.g., "Role Description must be between 10 and 200 characters").
- [ ]  Display an error message if the Role Name/ Description contains invalid characters (e.g., "Role Description can only include letters, numbers, spaces, and common punctuation marks").

### Acceptance Criteria

- [ ] The error message should appear below or beside the Role Name/Description input field.
- [ ] The error message should be styled consistently with other error messages in the application, using the same color and font.
- [ ] Ensure the Role Name/ Description input field itself is highlighted (e.g., with a red border) when an error message is displayed.

### Expected Outcome:
Admins are provided with immediate, clear feedback when they enter an invalid Role Name/ Description, ensuring that the form is only submitted with valid and properly formatted data.

### Images

![image](
<img width="855" alt="Screenshot 2024-08-22 at 12 24 01 AM" src="https://github.com/user-attachments/assets/922d8e46-bae0-46d8-8b6b-46332331dad3">

)

**Comment by delight-xxx** [comment]
@incredible-phoenix246 Kindly revert

**Comment by JoshuaAkpan** [comment]
I'm on it, I'll make a pr soon.
