### ISSUE TITLE
[FEATURE] Create the tab feature on the waitlist page

### ISSUE THREAD

**Issue by abel-otegbola** [hngprojects/hng_boilerplate_nextjs#111]
### Description
Develop the tab feature on the waitlist page. The tab feature should be visually appealing, responsive, and should include the following elements:

- Four tabs with icons and text contents same as the design
- Corresponding images when the tabs are changed
- Corresponding texts under the images

Ensure the tabs and images renders correctly with all required elements and the layouts are the same with the design.
Check that the section is responsive on all devices.

### Tasks
- [ ] Create the tabs, adding the icons and text contents
- [ ] Add state for toggling between tabs
- [ ] Make the tabs toggle to the next one automatically also
- [ ] Create the images for each tab and display only the corresponding image for the active tab
- [ ] Add the corresponding text content under the images
- [ ] Make the tabs and images responsive
- [ ] Write unit tests to ensure the tabs contains the icons and elements as expected.

### Figma
[Figma Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=799-10794&m=dev)

### Screenshot
![waitlist - features tab](https://github.com/user-attachments/assets/e80b63ae-f8d3-4248-892b-6692972a6970)
