### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > Paginated Table List of Template Items Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#118]
## Description
Create a Paginated Table List of Template List Items Component for HTML Templates used in the Super Admin Email Management Dashboard for creating and editing email templates.

## Acceptance Criteria
- Reusable Paginated List of Template List Items Component for HTML Email Templates
- Component has Template List Item Component displayed as a Table List
- Component has a fluid width
- Component adheres to the brand colors and design

## Expected Outcome

- User should be able to view a list of HTML Templates
- User should be able to navigate through the list using pagination
- Responsive design of Component

## Purpose
As a User, I want to be able to view a paginated list of my Email HTML Templates

## Requirement

-  Makes use of Pagination Component
-  Makes use of Template List Item Component

## Testing

- [ ] test pagination
- [ ] test action callback `onPreview` is passed to list items

## Task
- [ ] Implement Reusable Paginated Template List Component
- [ ] Maps and displays Tabular list of Template List Item Components
- [ ] Display Pagination
- [ ] Pagination should navigate through the list of HTML Templates
- [ ] Pass `onPreview` prop from parent to children list item components
- [ ] Component adheres to the brand design and color scheme
- [ ] Component has a fluid width and is responsive across devices

## Deadline
You are given till Saturday 20th July 10:00AM WAT to complete the task.

## Picture
![paginated templates](https://github.com/user-attachments/assets/a7ea8309-c294-483e-8212-6eed739897b3)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-9858&m=dev

**Comment by Engr-marcus** [comment]
Engr-marcus assigned
