### ISSUE TITLE
[FEATURE]: Email Templates > SuperAdmin Email Management Dashboard > Inbuilt Template Page

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#161]
## Description
Create a Paginated Table List of Template List Items Component for HTML Templates used in the Super Admin Email Management Dashboard for creating and editing email templates.

## Acceptance Criteria
- Reusable Paginated List of Template List Items Component for HTML Email Templates
- Component displays a preview of  an individual HTML Email Template when preview action is clicked
- Component has a fluid width and is responsive.
- Component adheres to the brand colors and design

## Expected Outcome

- User should be able to view a list of HTML Templates
- User should be able to preview individual HTML Email Templates
- Responsive design of Component

## Purpose
As a User, I want to be able to view a paginated list of my Email HTML Templates with a preview of individual templates by the side

## Requirement

-  Makes use of Template Preview Component
-  Makes use of Paginated Template List Items Component

## Testing

- [ ] test html template preview

## Task
- [ ] Page has tabs - New Template (active) and Manage Templates
- [ ] Page has title and description
- [ ] Page has breadcrumbs for easy navigation
- [ ] Displays Paginated Template List Items Component
- [ ] Retrieve html template from  `onPreview` callback from the Paginated Template List Items Component
- [ ] Display the retrieved html template using the Template Preview Component
- [ ] Preview action displays Template Preview Component with mode set to preview
- [ ] Component adheres to the brand design and color scheme
- [ ] Component has a fluid width and is responsive across devices

## Deadline
You are given till Saturday 20th July 11:00AM WAT to complete the task.

## Picture
![inbuilt_template_page](https://github.com/user-attachments/assets/e6e108b3-7501-4b64-8755-7a96c830a426)
![inbuilt_template_page_preview](https://github.com/user-attachments/assets/5024f3f8-7aea-4c49-85ee-3b724f94b2c7)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-9419&m=dev
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-9604&m=dev
