### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> Email template layout (Header and Footer)

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#165]
### Description

_Create an Email template layout (Header and Footer) according to the design_

### Acceptance Criteria

- The email template layout must be responsive
- The email template layout must be done according to the design
- The email template layout must be divided into header and footer

### Requirements	

The following items should be available for the layout

1. Header
2. Footer

### Tests

- [ ] Ensure template layout is responsive
- [ ] Ensure template layout can receive dynamic data according to what will be displayed
- [ ] Ensure template layout is displayed properly according to design and requirements

###  Tasks

- [ ] Create an email template header
- [ ] Create an email template footer
- [ ] Template header and footer must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template layout works as expected

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-30514&m=dev).

# IMAGES
![Header](https://github.com/user-attachments/assets/7f0b4ac0-c07a-43b5-8c0d-a86c2b7c8ec2)
![Footer](https://github.com/user-attachments/assets/c3457597-d4ae-420e-8790-05c530ccbe05)

**Comment by mrcoded** [comment]
Please add more to this issue @Saviourise

**Comment by Saviourise** [comment]
@mrcoded, the task is pretty straightforward. Is it that the task itself is too small or the task description is not enough?

**Comment by mrcoded** [comment]
it is too small @Saviourise
