### ISSUE TITLE
[Feature]: Email Templates > SuperAdmin Email Management Dashboard >HTML Template Editor Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#219]
### Description

Create an HTML Template Editor Component that displays Blocks of HTML Template, manages the layouts of the Blocks and converts the HTML template into Editor Block Components.

## Tasks
- [ ] Make Reusable Template Editor Component
- [ ] Responsive and adheres to brand colors and design
- [ ] Parses in-built html email template to Editor Blocks
- [ ] Works with the Editor Context via hook to handle functionalities
	- [ ] Manage moving the Editor Blocks upwards or downwards
	- [ ] Manage deletion of Editor Blocks
- [ ] Any other functionality as required by the design

## Related Components
Components are closely linked together and devs should ensure the components work together
- #185
- #205

### Notes
- You might need to liaise with the devs working on creating the different inbuilt HTML Templates to structure their templates using proper HTML5 to ease the conversion e.g each block should be wrapped in a `section` tag, footers in a `footer` tag.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=900-14308&m=dev)
| [`FIGMA LINK-2`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=900-17431&m=dev)

### Images

Editor displays Blocks of the HTML Template
![editor_block_main](https://github.com/user-attachments/assets/6864fcf4-2f6c-417d-8efd-bb158d92f7db)

Example Image of an In-Built Template
![email_template_inbuilt](https://github.com/user-attachments/assets/3053a0fe-9c09-419c-bd91-6956f80dcb1c)

**Comment by taiwoshalom** [comment]
test comment - pls ignore, testing something
