### ISSUE TITLE
[FEAT] External static page > landing page

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#22]
# **Description**
Implement both the desktop and the responsive mobile view for the external page landing page, excluding the header and the footer.

# **Acceptance Criteria**

- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Hero section
- Users section
- How it works section
- Client testimonials section
- Find the perfect fit section

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Saturday 11:59 pm WAT

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Write test for the implementations
- [ ] Proper commit message

# **Images**

![Boilerplate Landing Page](https://github.com/user-attachments/assets/3d34a9ec-109c-4740-87b1-0d7e1caf6668)

![Mobile View](https://github.com/user-attachments/assets/fe0a987b-a8d3-4f93-a2cc-ee003e3b16f5)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-24959&m=dev)
