### ISSUE TITLE
[FEAT] External Static Pages > Career Page > No search result component

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#222]
## Description

Develop the no search result component displayed on the career page in search state, when there is no search result

## Acceptance Criteria

- Create a no search result component which is shown when the user searches for a job and the result is not found.
- The image used on the component must be optimized.
- Make sure the correct search text is shown on the component.
- Write unit tests for this component to model expected behavior.
- The component should have props to support dynamicity such as search text, color, size, etc.

### Purpose

Provides a component for showing that there were no results matching the search query / text.

### Requirement

- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the component design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure that the correct search title is shown on the component

### Expected Outcome

- A no search result shown on the career page that shows when results are not found

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [ ] Create the component
- [ ] Include the required props (current search text is compulsory)
- [ ] Make the component responsive for mobile devices.
- [ ] Write unit tests to ensure the component works as expected.

### Links

- [Figma - Desktop](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1666-53651&t=pD9PTJul0udUOYKp-1)
- [Figma - Mobile](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=3990-7930&t=pD9PTJul0udUOYKp-1)

### Images

![Desktop View](https://github.com/user-attachments/assets/362d377d-b984-4243-95ab-cbd72b0090a8)
![Mobile View](https://github.com/user-attachments/assets/bf7ee3e3-d039-4701-9b8b-63ddf8d24b0f)

**Comment by chumex412** [comment]
This is too small a ticket. Merge the empty states for "No Available Jobs" and "No matching search results" as one ticket.

**Comment by skeby** [comment]
> This is too small a ticket. Merge the empty states for "No Available Jobs" and "No matching search results" as one ticket.
@chumex412 
The guy I was working with created the "No available jobs" as a separate ticket and it has been approved already

**Comment by chumex412** [comment]
Tell him to update the ticket to include both states and close this one.
