### ISSUE TITLE
[Feature]: Create Date Component Input on User Dashboard

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#223]
### Description

On the user dashboard page, Create a Date Range Input Box that will receive date inputs from a user and filter data from the Database using those date input ranges inputted by the user. This component will be used in the user dashboard page to view and download data within the date ranges specified by the user.

### Acceptance Criteria

- Implement the Date Range Input Component using this [guideline](https://ui.shadcn.com/docs/components/date-picker)
- Ensure the component is visually appealing and follow the design accordingly
- Maintain accessibility standards and arial labels
- The Component must be functional, accepting date ranges and filtering API endpoints by those date ranges.
- Accepts and validates users' input

### Task

- [ ] Develop the component based on the specific requirement
- [ ] Write unit test to ensure functionality of the component
- [ ] Ensure component receives inputs from the user
- [ ] Ensure component is fully responsive on all screens
- [ ] Verify accessibility features are properly implemented.
- [ ] Ensure the date ranges filters data correctly given the ranges
- [ ] Ensure input are well validated, users should not input futuristic date

### Test

- Ensure the component renders properly when imported
- Ensure responsiveness across various screen size
- Test that component receives date range inputs
- Test that date inputs are valid 
- Test that date inputs can actually filter endpoints by given dates

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-49735&m=dev)

### Images

![image]()
<img width="481" alt="Screenshot 2024-07-18 at 09 18 12" src="https://github.com/user-attachments/assets/5f0bd813-b956-4968-99b8-bf7e2f34ea42">

**Comment by Jay035** [comment]
Please when's the deadline for this
