### ISSUE TITLE
[FEAT] External Static Pages > About Us Page > Team Card component

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#224]
### Description

Develop the team card component displayed on the executive team section of the about us page.

### Purpose

Provides a component for showing executive team member's details in the about us page.

### Requirement

- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure that the icons are links to the respective social media platforms

### Expected Outcome

- A card component showing properties of the executive team members

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [x] Create a card component
- [x] Include links to the required platforms
- [x] Include props for the required properties (profile image, name, job role, etc.)
- [x] Include icon links to the social media platforms as shown in the design
- [x] Make the card component responsive for mobile devices.
- [x] Write unit tests to ensure the component works as expected.

### Acceptance Criteria

- Create a card component that the team member's profile image, name, job role/position, description, and social media links.
- This component must accept props for the properties mentioned above
- Write unit tests for this component to model expected behavior.

### Links

- [Figma - Desktop](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1541-6112&t=5os3steoueoSCIMy-1)
- [Figma - Mobile](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-20822&t=KGvl3Iwcr29gdaKA-1)

### Images

![Desktop View](https://github.com/user-attachments/assets/7b8c7771-7b07-4108-90e1-af3b2e56ecf2) ![Mobile View](https://github.com/user-attachments/assets/54931833-75fc-4460-8631-8a82794f9ccb)

**Comment by chumex412** [comment]
Please adjust the purpose section to fit with the other contents of the issue.

**Comment by skeby** [comment]
> Please adjust the purpose section to fit with the other contents of the issue.

@chumex412
Done
