### ISSUE TITLE
[FEAT] External Static Pages > Landing Page > Client Testimonials Cards

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#225]
### Description

Develop the client testimonial card displayed on the landing page

### Requirement

- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Make sure it is responsive on all screen sizes.

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [ ] Create a card component
- [ ] Include props for the mentioned properties (text content, ratings/stars, profile image, name, job role, etc.)
- [ ] Make the card component responsive for mobile devices.
- [ ] Write unit tests to ensure the component works as expected.

### Acceptance Criteria

- Create a testimonial card component that displays the text content, rating, profile image, name, job role, etc.
- Ensure pixel perfect implementation of the design.
- Make sure it is responsive on mobile devices
- Write unit tests for this component to model expected behavior.

### Links

[Figma Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-24959&t=94JTWERF3hKIGVKy-1)

### Images

![Desktop View](https://github.com/user-attachments/assets/317df045-f01d-45e9-8178-e1208267bed0) ![Mobile View](https://github.com/user-attachments/assets/b1348c17-3171-4b59-ba64-91e082570cd6)
