### ISSUE TITLE
[FEAT] External Static Pages > Pricing Page > FAQ Accordion

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#226]
### Description

Develop the accordion on the FAQ section of the pricing page.

### Requirement

- Make use of shadcn accordion to implement this accordion
- Ensure that the accordion design (border colors, background color, text content, etc.) remains consistent with the design.
- Make sure it is responsive on all screen sizes.

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [ ] Create an accordion component with shadcn.
- [ ] Include props for the title and accordion content
- [ ] Make the accordion component responsive for mobile devices.
- [x] Write unit tests to ensure the component works as expected.

### Acceptance Criteria

- Create an accordion component that displays the title, and the text content shown when the accordion is opened.
- Ensure pixel perfect implementation of the design.
- Make sure it is responsive on all screen sizes
- Write unit tests for this component to model expected behavior.

### Links

[Figma Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-20774&t=wAGOVHbSBceXSEjQ-1)
[shadcn accordion](https://ui.shadcn.com/docs/components/accordion)

### Images

![Desktop View](https://github.com/user-attachments/assets/2a5c61f6-31ab-4cb3-b1d4-4265164368cd) ![Mobile View](https://github.com/user-attachments/assets/598c914b-d9b3-49e0-a1da-c779059652bf)

**Comment by sheddyboy** [comment]
issue already exists 
https://github.com/hngprojects/hng_boilerplate_nextjs/issues/46
