### ISSUE TITLE
[FEAT] Implement Member Management Functionalities on Admin Dashboard

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#25]
Develop and implement functionalities to manage members on the Admin Dashboard using APIs. The functionalities include fetching members, search, filtering, reassigning roles, and deleting members. The implementation should use the member card component developed by another intern.

###Purpose
This feature will enable the admin to manage members seamlessly and efficiently on the dashboard. The admin can fetch members, search, filter, reassign roles, and delete members. This functionality will enhance the user experience by allowing quick access to member information and easy management of roles.

### Acceptance Criteria

**Requirements**

- UI - Develop the UI as seen on the design and must be responsive
- Search Members - Implement a search functionality using the appropriate API endpoints.
- Filter Members - Implement filter functionality using the appropriate API endpoints.
- Role Assignment - Implement functionality to reassign roles to members
- Delete Members - Implement functionality to delete members
- Fetch Members - Implement functionality to fetch and display members using the appropriate API endpoints.

**Tasks**

- [ ] Develop the UI as provided in the design.
- [ ] Responsiveness on all screens
- [ ] Develop the search component to query members based on search criteria.
- [ ]  Integrate with the appropriate API endpoints to fetch search results
- [ ] Display the search results using the member card component.
- [ ] Develop filter options to narrow down member results with the appropriate API endpoints to fetch filtered results and display the filtered results using the member card component.
- [ ] Write unit tests to cover different functionalities.

**Note**

- Ensure code quality and maintainability.
- Provide clear documentation and usage examples.
- Collaborate with the intern who developed the member card component for seamless integration.

**Deadline: Friday 12 Noon**
**Check #14 for the needed components**

**Images and Figma Link**
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=96-19505&m=dev
![Screenshot 2024-07-17 134635](https://github.com/user-attachments/assets/430e8f15-7558-4cc3-8836-1139875c066c)
![Screenshot 2024-07-17 134625](https://github.com/user-attachments/assets/27ca1b69-29e3-4f72-b611-7098d78e4126)
