### ISSUE TITLE
[FEAT] Organization settings > Manage Menbers > Sidebar

### ISSUE THREAD

**Issue by luqmonac56** [hngprojects/hng_boilerplate_nextjs#28]
### Description
Implement the Organization page sidebar where users can switch between Members, roles, and permission and Integration.

### Acceptance Criteria

1. The Sidebar is implemented according to the design
2. The sidebar should be visible on all pages unless explicitly hidden.
3. The sidebar should be collapsible and expandable by a toggle button.
4. Write a unit test for this component.

### Tasks
- [x] Implement the sidebar.
- [x]  Implement the functionality to toggle the sidebar (expand/collapse).
- [x] Add the navigation links to the Sidebar component according to the design.
- [x] Implement nested navigation items (submenus) in the sidebar according to the design.
- [x] Highlight the active navigation link according to design.

### Picture of the corresponding page of the ticket from the Figma:
![Settings Bar](https://github.com/user-attachments/assets/758ad2cc-e15b-4ace-a2bf-cedcd98f9c3c)

### Figma Link:
[figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=96-19490&m=dev)

## Timeframe
 - Friday, 8am

**Comment by oghene-ella** [comment]
There should be a shorter deadline for this... like friday 10am.
