### ISSUE TITLE
[FEAT] External Static Pages > Pricing Page > Pricing Plans > Pricing plans card component

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#30]
## Description

Develop the pricing cards displayed in the pricing page.

## Acceptance Criteria

- Create a pricing card component for displaying a pricing plan.
- This component should have props to facilitate dynamicity such as background color, border color, text, etc.
- This component should allow for mobile responsiveness when integrating into the pricing page.
- Write unit tests for this component to model expected behavior.

### Purpose

Provides a component for showing the pricing plan cards.

### Requirement

- Install/Re-use the shadcn button component for the action buttons on the cards and ensure the design is consistent with the design.
- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure that the component is responsive on mobile devices.

### Expected Outcome

- A component that displays the pricing plan using props to determine the type of plan (basic or premium) and so on.

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [x] Create a pricing plan card component
- [x] #227
- [x] Make the card component responsive for mobile devices
- [x] Write unit tests to ensure the component works as expected

### Links

- [Figma - Desktop](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-20774&t=6FU5xxnRLovCtQ8K-1)
- [Figma - Mobile](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-20822&t=6FU5xxnRLovCtQ8K-1)

### Images

![image](https://github.com/user-attachments/assets/9c28c4fd-2369-4715-90ff-ef4c5a6acc02) ![image](https://github.com/user-attachments/assets/619352b8-8140-4ba7-b99b-6bf32ee9678d)
