### ISSUE TITLE
[FEAT]: Create API Endpoint for User Login

### ISSUE THREAD

**Issue by Nainah23** [hngprojects/hng_boilerplate_nextjs#314]
### Description

Develop a new API endpoint to handle user login. The endpoint should accept user credentials (email and password) in the request body and return an authentication token upon successful login. It should handle invalid login attempts gracefully by returning appropriate error messages. Additionally, ensure a secure database design to store user credentials and implement tests to verify functionality.

### Acceptance Criteria

- The endpoint must successfully authenticate users with valid credentials.
- The endpoint must return a JSON Web Token (JWT) upon successful authentication.
- The endpoint must return a 400 error for missing or invalid input with an appropriate error message.
- The endpoint must return a 401 error for incorrect credentials with an appropriate error message.
- All responses must follow the specified structure.
- The database must securely store user credentials.
- Tests must be implemented to verify the correct functionality of the endpoint.

### Purpose

To provide a secure and standardized method for users to authenticate themselves, enabling access to protected resources. This includes implementing a robust database schema to store user credentials and ensuring thorough testing.

### Requirements

- **Endpoint:** /api/v1/auth/login
- **HTTP Method:** POST
- **Headers:** Content-Type: application/json
- **Request Body:**
  ```json
  {
    "email": "user@example.com",
    "password": "examplePass"
  }
  ```

- **Success Response (200):**
  ```json
  {
    "token": "jwt_token_here"
  }
  ```

- **Error Response (400):**
  ```json
  {
    "error": "Invalid request parameters",
    "message": "Email and password are required."
  }
  ```

- **Error Response (401):**
  ```json
  {
    "error": "Authentication failed",
    "message": "Invalid email or password."
  }
  ```

### Database Design

- **Table Name:** users
- **Columns:**
  - id (UUID, Primary Key)
  - name (VARCHAR, Not Null)
  - email (VARCHAR, Unique, Not Null)
  - password_hash (VARCHAR, Not Null)
  - created_at (TIMESTAMP, Default: Current Timestamp)
  - updated_at (TIMESTAMP, Default: Current Timestamp)

- **Example SQL:**
  ```sql
  CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );
  ```

#### Unit Tests

1. **Valid Credentials:**
   - Ensure a valid email and password return a 200 status and a JWT token.
2. **Invalid Email or Password:**
   - Ensure invalid credentials return a 401 status and the appropriate error message.
3. **Missing Parameters:**
   - Ensure requests missing the email or password return a 400 status and the appropriate error message.

#### Integration Tests

1. **Database Connection:**
   - Verify that the endpoint correctly interfaces with the database to authenticate users.
2. **JWT Token Generation:**
   - Ensure the JWT token is correctly generated and includes the necessary payload.

### Tasks

1. **Design Database Schema:**
   - [ ] Create the users table with the specified columns.

2. **Develop API Endpoint:**
   - [ ] Implement the /api/v1/auth/login endpoint.
   - [ ] Ensure it correctly processes the request body and generates a JWT token.
   - [ ] Handle missing or invalid input appropriately.

3. **Integrate Authentication Logic:**
   - [ ] Implement the logic to authenticate users using the email and password.
   - [ ] Ensure secure handling of passwords (e.g., hashing).

4. **Implement Tests:**
   - [ ] Write unit tests to cover all cases (valid credentials, invalid credentials, missing parameters).
   - [ ] Write integration tests to ensure database connectivity and JWT token generation.

5. **Documentation:**
   - [ ] Document the API endpoint, including request/response bodies, success, and error codes.
   - [ ] Ensure the documentation is accessible and understandable for future developers.

6. **Code Review and Testing:**
   - [ ] Conduct a code review to ensure best practices and security measures.
   - [ ] Perform thorough testing to ensure the endpoint works as expected.

7. **Deployment:**
   - [ ] Deploy the endpoint to the appropriate environment.
   - [ ] Ensure the necessary configurations and environment variables are set for JWT and database connections.

### Expected Outcome

A functional API endpoint that allows users to log in using their email and password, receiving a JWT for authentication. The endpoint will enhance security and user experience by providing a reliable authentication mechanism. The database will securely store user credentials, and tests will ensure the endpoint functions correctly and securely.

**Comment by Nainah23** [comment]
**Team Members’ Slack IDs:**
Naina - NodeJS
Covenant12 - laravel PHP 
Deola Deosun - python 
Synth - Go
Meysdays - Java

**Comment by buka4rill** [comment]
You need something like this
![CleanShot 2024-07-17 at 18 10 59](https://github.com/user-attachments/assets/0ffba0e9-a1f2-4e1e-9902-dc23c3e64a39)

**Comment by Nainah23** [comment]
Updated the tasks section

**Comment by nedssoft** [comment]
@Nainah23 it should be

`api/v1/login`

Also, this endpoint is related to [#140](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/140), both should align, something like `api/v1/auth/login`

**Comment by Nainah23** [comment]
> @Nainah23 it should be v1 before api
> 
> `v1/api/login`
> 
> Also, this endpoint is related to [#140](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/140), both should align, something like `v1/api/auth/login`

I have updated the endpoint

**Comment by NdubuisiJr** [comment]
Follow the approved Api route versioning pattern. And a user needs to have a name na.

**Comment by Nainah23** [comment]
Updated the api route versioning pattern and added the name column
