### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > New Template with HTML

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#32]
## Description
Create the Page for Generating New Email Template with HTML found in the Super Admin Email Management Dashboard

## Acceptance Criteria
-  Reusable Breadcrumbs
- Page title and description
-  Well validated form with input and button submission
- Tips Component with a defined title and bulleted tips
- Components adheres to the brand colors and design
- Responsive design of page

## Expected Outcome

- User should be able to see a tips card for helpful information
- User should be able to input or paste link to a html file in the input field
- User should be able to click the button to generate the new html template
- On success, user should be directed to the preview generated html page

## Purpose
As a User, I want to input a link pointing to my Html file to generate a new email template

## Requirement

-  Installs and uses shadcn-ui alert
-  Makes use of the form, Input and button components
-  Makes use of the Breadcrumbs component

## Testing

- [ ] test for input validation
- [ ] test for link submission
- [ ] test for template generation

## Task
- [ ] Has Breadcrumbs for easy navigation
- [ ] Implement Page with a clear title and description
- [ ] Implement Tips component using shadcn-ui alert
- [ ] Implement Form input with label and button
- [ ] validate that link from form input points to .html file
- [ ] button generates template on form submission
- [ ] navigate to preview template page on successful template generation
- [ ] Components adhere to the brand design and color scheme
- [ ] Page is responsive across device widths

## Deadline
You are given till Saturday 20th July 10:00AM WAT to complete the task.

## Picture
![generate_email_template](https://github.com/user-attachments/assets/c60ee564-7caf-4bde-83d8-f746264c1d8e)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=63-69677&m=dev

**Comment by kingbary** [comment]
I can't assign this issue to myself

**Comment by kingbary** [comment]
@oreoluwa212 I have tested and confirmed it's working well. Please review!
