### ISSUE TITLE
[FEATURE] Implement User Dashboard > Product > Star Rating Component

### ISSUE THREAD

**Issue by Petersonbabs** [hngprojects/hng_boilerplate_nextjs#339]
# Description
Develop a star rating component for the user dashboard's product detail and product reviews list. Use React-Rating-Stars component library to achieve the design and functionality. This component should be intuitive, visually appealing, and responsive.

# Purpose
This component will be used in two places: user dashboard > product detail and product reviews card item. The purpose of this component is to allow users to see the overall and individual ratings on each one of their products.

# Requirements
- Make use of **[react-rating-stars](https://www.npmjs.com/package/react-rating-stars-component)**  (Note: Do not install this library by yourself. Reach out to a mentor).
- Ensure that the design is the exactitude of what's in the Figma link provided below.
- Ensure the component is responsive and functions well on various devices (desktop, tablet, mobile).
- Include props like the amount of reviews, reviews data, etc.

# Testing 
- Use React Testing Library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Put yourself in the shoes of the user to test different cases of using this component.

# Task 
- [ ] Create a start rating component using the react-rating-stars component library.
- [ ] Ensure that the component looks appealing and is responsive on various screen sizes.
- [ ] Add props to receive the number of reviews coming and the corresponding rates.
- [ ] Add the relevant content around the icon. e.g '4.3', (46 reviews)
- [ ] Write unit tests to ensure the component works as expected.

# Acceptance Criteria
- The component must be functional and dynamic. The degree of highlighted icons is based on the actual reviews.
- The component is responsive on various screen sizes.
- You've written a unit test for the component to model its behavior.

# Links
- **[Figma Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=619-31487&t=QVyAASdVi2hpOWTP-1)**
- **[React-stars-rating component doc](https://www.npmjs.com/package/react-rating-stars-component)**

# Images
![Frame 1257](https://github.com/user-attachments/assets/2185be5b-9bd4-47ae-aecd-5312f7dd115c)

**Comment by williamwebs** [comment]
Can this task please be assigned to me.
