### ISSUE TITLE
[FEAT] Implement Invite Member Functionality with Generated Link

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#34]
Develop and implement the functionality for inviting members via a generated link that can be copied to the clipboard. Admins should be able to toggle the invite link feature, generate a new link, refresh to get another link, and copy it to the clipboard. The implementation should use the appropriate components such as Buttons, InputField, and Toggle Switch.

### Purpose
Admins of an organization should be able to invite members to their dashboard with ease by using an auto-generated link. This link can be copied to the clipboard and shared with potential members, allowing them to gain access to the organization's dashboard.

### Acceptance Criteria
**Requirement**

- UI - UI must be as seen on design and must be responsive across screen different sizes
- Switch Function: Admin should be able to switch between enabling and disabling the invite link feature.
- Link Display: Display the link input field using data from the appropriate API endpoints when the switch is enabled
- Copy to Clipboard: Implement functionality to copy the generated link to the clipboard
- Refresh Link: Implement functionality to refresh and generate a new link.
- Use of Components: Ensure the correct usage of Buttons, Input Field, and Toggle Switch components.

**Tasks**

- [ ] Implement a toggle switch to enable or disable the invite link feature.
- [ ] Fetch and display the generated link from the appropriate API endpoints when the switch is enabled.
- [ ] Implement functionality to copy the displayed link to the clipboard with proper feedback provided.
- [ ] Implement functionality to refresh and generate a new link from the apprropriate API endpoint and update display
- [ ] Ensure the correct usage of Buttons for actions like copying and refreshing the link.
- [ ] Write unit tests to cover different functionalities.

**Deadline: Friday 10am**

**Note**

- Ensure code quality and maintainability.
- Provide clear documentation and usage examples.
- Collaborate with the team to ensure seamless integration with existing components.

Images and Figma Links
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=96-100124&m=dev
![image](https://github.com/user-attachments/assets/902d1e01-3b5d-4168-8c59-e1b725abd4ed)
![image](https://github.com/user-attachments/assets/2a325015-4ee3-402e-9cf8-eb2c74dc4e7d)

**Comment by oghene-ella** [comment]
deadline should be like friday 10am...

**Comment by kiisi** [comment]
Please I can't assign this issue to myself too
omo
