### ISSUE TITLE
[FEAT] External Static Pages > Navbar component

### ISSUE THREAD

**Issue by skeby** [hngprojects/hng_boilerplate_nextjs#39]
## Description

Develop the navbar displayed on all the pages.

## Acceptance Criteria

- Create a navbar component that displays the app logo, navigation links, and login and get started buttons.
- This component should have props to allow for a logged in and logged out state (meaning, the login and get started buttons should only be shown when the user is not logged in)
- This component should allow for mobile responsiveness.
- Write unit tests for this component to model expected behavior.

### Purpose

Provides a component for showing the navbar.

### Requirement

- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure that the logo is a link to the home route of the application.
- Ensure that the component is responsive on mobile devices by displaying the hamburger shown in the design and implementing the mobile navbar that shows when the hamburger is clicked.
- Ensure that the authentication related buttons (login and get started) are not shown when the user is logged in.
- Ensure that the title of the current page is highlighted as shown in the design.
- Ensure that the profile and notification are shown when the user is authenticated.

### Expected Outcome

- A component that displays the navigation bar on all pages.

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [ ] Create a navbar component
- [ ] Account for authenticated state by removing the login and getting started buttons when user is logged in and showing the notification and profile.
- [ ] Integrate the shadcn button component for the buttons on the component.
- [ ] Make the navbar responsive for mobile devices.
- [ ] Write unit tests to ensure the component works as expected.

### Links

- [Figma - Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2202-24958&t=CsLBkn7OTy2kXjPu-1)

### Unauthenticated Navbar
![image](https://github.com/user-attachments/assets/af9babc1-35c9-4d83-99c0-a680be36fb02)

### Authenticated Navbar
![image](https://github.com/user-attachments/assets/18ef532e-d09d-40b5-9cbe-250faf49cd6f)

### Mobile Navbar
![image](https://github.com/user-attachments/assets/e481d7dc-7145-4904-bfcf-8167bfbc71bc)

**Comment by henrymishael** [comment]
I am working on this already..thank you
