### ISSUE TITLE
[FEAT] - Authentication Page -> Sign Up Default

### ISSUE THREAD

**Issue by Justfemi** [hngprojects/hng_boilerplate_nextjs#4]
### Description
Implement the Sign Up default page as shown in the design

### Acceptance Criteria
- Responsive across all screen sizes (desktop, tablet and mobile)
- Write tests for your code.
- Add validation to all fields as shown in the design. Refer to the Email/Error Page
- Use components where necessary (header, footer, buttons, input fields and so on)
- Implement a focus state on all input fields.
Refer to the Email/Filling page.

### Tasks 
- [x] Implementation of the sign up page.
- [x] Validation of all input fields showing the appropriate error messages 
- [x] This page should be responsive on all screen sizes 
- [x] Write unit test for your implementation.

### Timeframe
24 hours

[Link to Design](
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1-17895&t=p2gECcZQmYqvvrn7-4) 

### Preview
![Sign up Default](https://github.com/user-attachments/assets/ee3aeb9f-371b-4770-8835-4992075fbf96)

**Comment by lerderl** [comment]
Kindly check this link as a guide to edit this issue appropriately with the right sections [https://github.com/hngprojects/hng_boilerplate_nextjs/issues/5](url)

Also, it shouldn't be only an individual default page state that should be implemented from the figma design.

Implement the Email/Filling and Email/Error page states as well for an individual signing up.

**Comment by omotayobolu** [comment]
I'll be working on this.
