### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > Template Preview Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#43]
## Description
Create the Preview Component for HTML Templates used in the Super Admin Email Management Dashboard for creating and editing email templates.

## Acceptance Criteria
- Reusable Preview Component for HTML Templates
- Component adapts to scrollable Templates
- Components shrink templates to fit
- Component has a fluid width
- Component adheres to the brand colors and design

## Expected Outcome

- User should be able to view any HTML Template
- User should be able to scroll the Template if longer than the Preview Component
- User should be able to edit the HTML markup
- Responsive design of Component

## Purpose
As a User, I want to be able to preview or edit Html Email Templates

## Requirement

-  custom scrollbar design

## Testing

- [ ] test Preview Component has a fluid width
- [ ] test Preview Component can scroll its content
- [ ] test Preview Component accepts template prop of html content
- [ ] test Preview Component accepts mode prop - preview and edit

## Task
- [ ] Implement Reusable Preview Component
- [ ] Component has a scrollable content
- [ ] Scrollbar is visible when content overflows its container
- [ ] Make Preview Component responsive with a fluid width
- [ ] Preview Component should render html template as prop
- [ ] Preview Component should have a prop 'mode' - preview and edit
- [ ] Preview mode (the default) displays the HTML template
- [ ] Edit mode displays the HTML Markup as content editable 
- [ ] Supports `onEdit` / `onChange` callback to pass edited markup
- [ ] HTML Template scales to fit its container
- [ ] Component adheres to the brand design and color scheme

## Deadline
You are given till Saturday 20th July 10:00AM WAT to complete the task.

## Picture
![preview_email_template](https://github.com/user-attachments/assets/a5890c7a-6a5b-4f29-87f1-d6b4f3f816e9)
![preview_email_template_scaled](https://github.com/user-attachments/assets/9f1cc561-5800-476c-95ed-0cb14ca92ece)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2266-27056&m=dev
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-10446&m=dev

**Comment by Samadeen** [comment]
Kindly confirm this isn't a duplicate

**Comment by elitenoire** [comment]
> Kindly confirm this isn't a duplicate

No it is not, It is a standalone component to preview HTML Email Templates.

**Comment by elitenoire** [comment]
@Samadeen I mean the Preview Component in both images are the same. It is used in the two places linked in the figma file

**Comment by Samadeen** [comment]
Understood ma'am.
