### ISSUE TITLE
[FEATURE] Create Accordion Component

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#46]
## Description
Develop an Accordion Component. This component will be implemented in the pricing page to list all FAQs. The Accordion component should not drop down more than 1 item.

## Acceptance Criteria

- The accordion component should be implemented according to the design [Use this as guideline](https://ui.shadcn.com/docs/components/accordion)
- Ensure the accordion component is responsive in all screen sizes
- Write test for your component

### Requirements
**The prop should receive the Accordion Header, the question, and the Accordion content, the response**

### Test Script

- Ensure the component renders the requirements accordingly
- Ensure the component receives the accordion header, the question.
- Ensure the component receives the accordion content, the response.

## Tasks

- [x] Develop the component based on the requirements and design
- [x] Make component responsive on all screens
- [x] Write unit test for the component

### Link
[Accordion](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-20796&m=dev)
