### ISSUE TITLE
[Feature]:  Settings page Pages > Navbar component

### ISSUE THREAD

**Issue by luqmonac56** [hngprojects/hng_boilerplate_nextjs#465]
## Description

Develop the navbar displayed on all the pages.

### Purpose

Provides a component for showing the navbar.

### Requirement

- Ensure that the typography (text colors, font weights, font sizes, etc.) remain consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure that the logo is a link to the home route of the application.
- Ensure that the component is responsive on mobile devices by displaying the hamburger shown in the design and implementing the mobile navbar that shows when the hamburger is clicked.
- Ensure that the profile and notification are shown when the user is authenticated.

### Expected Outcome

- A component that displays the navigation bar on all pages.

### Testing

- Make use of react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real life use of the component

### Task

- [ ] Create a navbar component and use all expected reuseable components.
- [ ] Make the navbar responsive for mobile devices.
- [ ] Write unit tests to ensure the component works as expected.

### Links

- [Figma - Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-17064&m=dev)

### Images

![Top Navigation](https://github.com/user-attachments/assets/4baf8ad2-5ecf-4ee9-99af-17ce47ff7fa7)

## Acceptance Criteria

- Create a navbar component that displays the app logo, navigation links, aand every other things according to the design
- This component should allow for mobile responsiveness.
- Write unit tests for this component to model expected behavior.

### Links

- [Figma - Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-17064&m=dev)

### Images

![Top Navigation](https://github.com/user-attachments/assets/4baf8ad2-5ecf-4ee9-99af-17ce47ff7fa7)
