### ISSUE TITLE
[FEAT] External static Page > Job details page

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#54]
# **Description**
Implement both the mobile and web view of the job details page . Implement every content in the page excluding the header and the footer, use already made header and footer if there is a need to. Make use of custom Hero section if need be.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Page breadcrumb
- Page content

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Saturday 11:59 pm WAT

# **Tasks**
- [x] Implement all the sections in the design
- [x] Responsiveness across all screens
- [x] Make use of reusable components where needed
- [x] Write test for the implementations
- [x] Proper commit message

# **Images**
![Job details](https://github.com/user-attachments/assets/f6a18842-41b3-4c28-babe-c917c98d056d)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-24164&m=dev)
