### ISSUE TITLE
[FEAT] AUTHENTICATION PAGE - OTP / VERIFICATION CODE input component

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#58]
### Description

_Implement the Inputs that are responsible for accepting OTP code or Verification code according to the design. The inputs should be dynamic and will be responsible for inputing OTP and verification codes._

### Acceptance Criteria

- The inputs have to be done according to the design.
- The inputs should be responsive and not be disrupted on different screens
- Each input should have an onchange function
- The inputs component should return an appended data of all the individual inputs e.g (148372)
- Each input in the component should be able to recieve only one character 
- The next input should automatically be focused when the a character has been typed in the previous input

### Requirements

The following props should be available for the component

1. Normal input props
2. A dynamic number of inputs to display
3. An input data prop to get the inputs data on any input change

### Testing

1. Ensure inputs are displayed properly according to design and requirements
2. Ensure user cannot type in multiple characters in one input
3. Ensure the correct number of inputs are displayed according to what is provided in the props
5. Ensure the appended individual input data is returned on any input change

### Tasks

- [ ] Create the input component
- [ ] Design an input that will be mapped by the number of inputs props. Each input should include the hover and active states
- [ ] Write an onchange function that takes the input data, appends it with other inputs data, stores the appended data in a state and returns the stored data
- [ ] Write unit tests to ensure that the component works as expected
- [ ] Test the component for responsiveness and functionality

### Timeframe

**This task must be completed on or before Friday 11:59 pm as other components depends on this component** 

### Images
![Screenshot 2024-07-17 145544](https://github.com/user-attachments/assets/a227ec54-cd74-4d09-a4c1-b1b15e82cc26)
![Screenshot 2024-07-17 145603](https://github.com/user-attachments/assets/f7bb1cb6-4cac-40bf-ac45-86814616167c)

### Links
Figma Link
[https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1-18132&m=dev](url)
