### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > Preview Page

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#61]
## Description
Create the Preview Page to view Generated HTML Templates used in the Super Admin Email Management Dashboard

## Acceptance Criteria
- Page has breadcrumbs for easy navigation
- Page has a title and description
- Page has an action button to edit content - Generated HTML Design
- Page adheres to the brand colors and design
- Page is responsive across device widths

## Expected Outcome

- User should be able to view the Generated HTML Template
- User should be able to edit the content of the Generated HTML Template
- Responsive design of Page

## Purpose
As a User, I want to be able to preview and edit the Generated Html Email Templates

## Requirement

-  makes use of the Template Preview Component

## Testing

- [ ] test Action Button toggles edit or preview mode of Template Preview Component 
- [ ] test generated HTML template can be edited

## Task
- [ ] Page should have Breadcrumbs
- [ ] Pages should have title, description and Action Button
- [ ] Render the Template Preview Component
- [ ] Action Button toggles between preview and edit template
- [ ] Save edited HTML template or discard edits

## Deadline
You are given till Saturday 20th July 11:00AM WAT to complete the task.

## Picture
![preview_template](https://github.com/user-attachments/assets/8daefc12-6538-4556-ba10-dc994f0b31f7)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=91-30346&m=dev

**Comment by SheCode287** [comment]
assigning this to myself
