### ISSUE TITLE
[FEAT] External static page > Floating footer cookie consent component

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#63]
# **Description**
Implement the floating footer cookie consent component, make use of the custom button component.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- All components content as seen in the desgin
- Make use of resuable button components

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Saturday 11:59 pm WAT

# **Tasks**
- [x] Implement all the sections in the design
- [x] Responsiveness across all screens
- [x] Make use of reusable components where needed
- [x] Write test for the implementations
- [x] Proper commit message

# **Images**
![Frame 26](https://github.com/user-attachments/assets/71e25364-0a0a-4ab0-9306-7f659a7ce7d4)
![Frame 26 (1)](https://github.com/user-attachments/assets/41f2f3b1-7a17-47b2-a219-88d03beb6746)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-23848&m=dev)
