### ISSUE TITLE
[FEAT] External Dynamic Pages > Blog Post header

### ISSUE THREAD

**Issue by kleenpulse** [hngprojects/hng_boilerplate_nextjs#69]
## Description
Develop a reusable Blog Post Header component. This component will be used at the top of individual blog post pages. The Blog Post Header should be visually appealing, responsive, and should include the following elements:

## Acceptance Criteria
- Implementation must be responsive
- All buttons should be functional
- Implementation must be pixel perfect

### Requirements	
The component should receive the following props:

- Title
- Subtitle
- Date
- Author name
- Author profile picture
- Tag
- Time of reading
- Blog Image (background image or main image)
- Excerpt

### Testing

- Ensure the component is responsive and renders correctly with all required elements
- Check that the component handles any length of texts (long titles, missing images) no weird layout shifts.

### Tasks

- [ ]  Develop the Blog Post Header component based on the provided requirements.
- [ ] Design should be responsive on all screens.
- [ ] Run tests to ensure the component works as expected.
- [ ] the component should receive props as described above under requirements.

# Link
[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-25687&m=dev).
### 
![image](https://github.com/user-attachments/assets/e85fab36-1a66-48f7-9966-6293fd58cc39)

**Comment by JulianaSau** [comment]
> Design both portrait and landscape versions.

This statement has such a wide interpretation. It should be responsive across all screens. 
The component should also receive props concerning number of comments and likes
Also, your figma link should lead to the exact component being designed. Update it

**Comment by kleenpulse** [comment]
@JulianaSau fixed

**Comment by SheCode287** [comment]
is anyone working on this?

**Comment by kingstech001** [comment]
yes

**Comment by kingstech001** [comment]
I'm working on it

**Comment by SheCode287** [comment]
cool

**Comment by Cerr1738** [comment]
why was i unassigned?

**Comment by JulianaSau** [comment]
this is on a first come first serve basis
@kingstech001 was the first so by that logic he should be the only one working on this issue. The rest of you find something else to do

**Comment by kingstech001** [comment]
@JulianaSau thank you

**Comment by kingstech001** [comment]
please check this figma link it is not what was seen in it that I'm seeing now

**Comment by kingstech001** [comment]
@kleenpulse  check this figma link again please

**Comment by kingstech001** [comment]
@JulianaSau please check that figma link the issue I'm working on is not in it
