### ISSUE TITLE
[FEAT] Organization settings  > Integration page > Implement daily used app component

### ISSUE THREAD

**Issue by luqmonac56** [hngprojects/hng_boilerplate_nextjs#70]
### Description
Implement the daily used app component on the integration default page.

### Acceptance Criteria

1. The component is implemented according to the design
2. The component should be responsive  across all screen sizes according to design.
3. The component should accept children props.
4. Write a unit test for this component.
5. Use the toggle component  this component to make it more reuseable

### Tasks
- [ ] Implement the daily used app component.
- [ ] Allow the component to accept children props.
- [ ] The toggle component should be used in this component 

[figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1623-11744&m=dev)

### Picture of the corresponding page of the ticket from the Figma:
![Frame 1000001699](https://github.com/user-attachments/assets/33276d48-1f29-4fb7-8bf6-5ab9ab5691c0)
