### ISSUE TITLE
[FEATURE] Create User Dashboard Revenue Card Component

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#87]
## Description
Create a Card Component that will be used in the User Dashboard Product Listing Page. The card component shows the Total Revenue made from the previous month. The revenue should be formatted in currency with it's currency symbol

## Acceptance Criteria

- The component must be implemented accordingly with the design
- The component should be fully responsive
- Icons or Images need to adhere to accessibility standards

### Requirements
**The component should receive the following props:**

- Title of the card
- Revenue amount formatted in currency
- Performance index from the last month
- Currency should be configurable within the card

### Test Script

- Ensure the component renders appropriately with all required elements
- Ensure all props are collected to avoid view breaks
- Ensure it is mobile responsive
- Ensure amount is in currency format

### Tasks

- [ ] Develop the Revenue Card component based on the provided requirements.
- [ ] Develop a responsive revenue card component
- [ ] Implement revenue card component
- [ ] Write unit test to ensure component should work appropriately
- [ ] Encapsulate all amount in currency format
- [ ] The currency symbol should be configurable within the component. When implemented, developers should be able to choose the desired currency symbol. Use Intl.NumberFormat to handle the currency formatting.

### Link 
[Revenue Card Component](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=528-22069&m=dev)

### Image
<img width="733" alt="Screenshot 2024-07-17 at 16 37 10" src="https://github.com/user-attachments/assets/de7cd197-59d2-4ae2-8907-f24b0878c743">

**Comment by Meekaylah** [comment]
Add a task that allows the currency symbol to be configurable within the component. When implemented, developers should be able to choose the desired currency symbol. Use Intl.NumberFormat to handle the currency formatting.

**Comment by judeb21** [comment]
Okay, done @Meekaylah
