### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > Page

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#9]
## Description
Create the Page for the Super Admin Email Management Dashboard for creating new email templates and managing old email templates.

## Acceptance Criteria
-  Must have a Tab - New Template & Manage Templates
-  New Template Tab must have a clear title and description
-  New Template Tab must be the default tab
-  New Template Tab must have two options that navigates to another route
	-	Generate with HTML
	-  Edit In-built Template
- Components adheres to the brand colors 

## Expected Outcome

- User should be able to switch between creating a new email template or managing old email templates tabs.
- User should be able to navigate to the Generate with HTML page
- User should be able to navigate to the Edit In-built Template page
- Responsive design of Page

## Purpose
As a User, I want to have options of Creating a New Email Template or Managing my Old Email Templates

## Requirement

-  Installs and uses shadcn-ui tabs
-  Uses links to navigate pages

## Testing

- [ ] Unit test for tabs
- [ ] Unit test for template options

## Task
- [ ] Implement Tabs - New Template & Manage Templates using shadcn-ui tabs
- [ ] Tabs adhere to the brand design and color scheme
- [ ] Tabs should be switchable
- [ ] New Template is the default tab
- [ ] Implement Tab Content with a clear title and description
- [ ] Implement  Reusable Template Options - Generate with HTML & Edit In-built Template
- [ ] Each Template option should have an icon, title and description and hover state
- [ ] Each Template option should link to the selected page
- [ ] Make page responsive

## Deadline
You are given Friday, 19th July 10PM WAT to complete the task.

## Picture
![create_email_template](https://github.com/user-attachments/assets/bb043235-7212-4763-8ec9-a383c0b33631)
![create_email_template-hover](https://github.com/user-attachments/assets/8f22b343-ace9-42b9-ab8a-af1501096241)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=63-92444&m=dev

**Comment by Lucky-tech10** [comment]
Provide links to the ShadCN components need for page

**Comment by MazinoCodes** [comment]
@ebtaryoh  please where is the page
