### ISSUE TITLE
[FEAT] Email Templates > SuperAdmin Email Management Dashboard > Template List Item Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#93]
## Description
Create a Template List Item Component for HTML Templates used in the Super Admin Email Management Dashboard for creating and editing email templates.

## Acceptance Criteria
- Reusable List Item Component for HTML Templates
- Component has Preview action attached
- Component links to an edit page of the HTML Template
- Component displays an image of the HTML Template
- Component has a Title
- Component has a fluid width
- Component adheres to the brand colors and design

## Expected Outcome

- User should be able to view a thumbnail image of the HTML Template
- User should be able to view the title of the HTML Template
- User should be able to click on the Preview action
- User should be able to navigate to the Edit page using the edit link
- Responsive design of Component

## Purpose
As a User, I want to be able to view an image and title of HTML Template and have quick access to to preview and edit the Template.

## Requirement

-  html-to-image library

## Testing

- [x] test Component has a fluid width
- [x] test Component accepts title, template and `onPreview` props
- [ ] test Component converts html template to image
- [ ] test Component displays a thumbnail image of the template
- [ ] test Component links to edit page of the HTML Template when edit link is clicked
- [ ] test Components passes html template to `onPreview` prop when preview action is clicked

## Task
- [x] Implement Reusable Template List Item Component
- [x] Accepts Title Prop
- [x] Accepts Template prop
- [x] Accepts `onPreview` Prop
- [x] Pass Template to `onPreview` callback prop when preview action is clicked
- [ ] Link to the Edit Page of the HTML Template when edit link is clicked
- [ ] Convert Html Template received from prop to image
- [x] Displays a thumbnail image of the HTML Template
- [x] Implement hover and selected variant
- [x] Component adheres to the brand design and color scheme
- [x] Component has a fluid width and is responsive across devices

## Deadline
You are given till Friday 19th July 11:59PM WAT to complete the task.

## Picture
![template_list_item](https://github.com/user-attachments/assets/8330f76d-4906-45e7-9010-2faa32f8b546)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-9860&m=dev

**Comment by Petersonbabs** [comment]
This ticket was assigned to me petersonbabs by Abdul.tsx . .. Move on please
