### ISSUE TITLE
[FEAT] Waitlist - Create the hero section of the waitlist page

### ISSUE THREAD

**Issue by abel-otegbola** [hngprojects/hng_boilerplate_nextjs#99]
Description
Develop the waitlist hero section. The hero section should be visually appealing, responsive, and should include the following elements:

- heading
- text
- Emphasized text
- Button

- 4 cards - Find the hero cards created in issue #53 .

Ensure the component renders correctly with all required elements and the layouts are the same with the design.
Check that the section is responsive on all devices.

### Tasks
- [ ] Develop the waitlist hero section based on the provided requirements.
- [ ] Add the cards and make them responsive to different screen sizes
- [ ] Write unit tests to ensure the section contains the elements as expected.

### Figma
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=518-7981&m=dev

### Screenshot
![waitlist hero](https://github.com/user-attachments/assets/45ea97f9-1595-486d-9585-eed9ef931802)
